### PR TITLE
New funcionality

### PR DESCRIPTION
**Pull request by scpalbright**
- Basic bucket object to compute bucket parameters and return bunch outlines for given length/dE/emittance
- Simple assertions for e.g. array length comparisons
- Updated exceptions and inheriting all from BLonD_Exception to allow general catching of internal errors
- Minor changes in profile object, removed deprecated version
- Created first attempt at induced voltage object
- Added delta_E interpolating function to Ring object for cases where interpolation is not turn-by-turn
- Added interpolation module to handle different types of interpolation, only cubic included so far
- Added potential_to_hamiltonian function for general cases conversion from potential well to hamiltonian
- Unit tests for bucket and impedance_sources objects.  Induced_voltage to follow after discussion on functionality and cross-checking of implementation.

### CODE REVIEW

**Comment by scpalbright** [comment]
>     * For the Bucket class, could you please present some simple usage/examples in the next meeting?
Yes
>     * For the changes in impedance sources, do we need more testing?
Yes
>     * Concerning the dE calculation in Ring, in which cases the interpolation is not done on a turn-by-turn basis?
Things like designing voltage functions or analysing MD data in the _Design and _Data versions.

**Comment by scpalbright** [comment]
Travis failing because Python 3.5 has an older version of unittest.mock(), I can put the use case in a Try/Except loop, or just leave it.  Thoughts?

**Comment by alasheen** [comment]
- I would consider having the Bucket object and its module in the rf_function package. Like this there would be the "potential.py" module with simple standalone functions, and the more advanced "bucket.py" right next to it (package/modules to be renamed for clarity?).
- We should probably drop support for Python 3.5 like we did for BLonD, and use Python 3.6-3.7 in Travis (3.8 was still causing other issues)

**Comment by scpalbright** [comment]
That could work.  Let's discuss alternative namings at the next BLonD meeting.

**Comment by scpalbright** [comment]
@kiliakis could you modify the Travis set up to use Python 3.6 and 3.7, and remove 3.5?  All the test should then pass and this pull request can be accepted if there are no other issues.

**Comment by kiliakis** [comment]
Sure, give me few mins

**Comment by scpalbright** [comment]
Ballsed up a merge conflict on master.  Need to fix it before pull can be accepted.

**Comment by scpalbright** [comment]
Closing this pull request as the master got updated by accident.  New pull request created from the correct version of master.

**Pull request closed without merging**
